---
spring:
  cloud:
    config:
        git:
          uri: https://github.com/kennyk65/Microservices-With-Spring-Student-Files
          searchPaths: ConfigData
        # "native" is used when the native profile is active, for local tests with a classpath repo:
        native:
          searchLocations: classpath:offline-repository/
server:
  port: 8001